### ISSUE TITLE
Missing documentation non public functions

### ISSUE THREAD

**Issue by StefanMaron** [365businessdev/vscode-alxmldocumentation#17]
Is it intentional that the info about mission documentation is shown on non public functions?

in detail:
- local fuctions
- event publishers
- test functions / codeunits

also maybe triggers like OnAfterGetRecord should not needed to be documented because there should not be any code except function calls inside

**Comment by sirhc101** [comment]
Hello Stefan,

yes, it's intended because in our point of view documentation belongs to each procedure, even publishers and local functions. Well, while thinking about it I would agree with you regarding the test procedures, because if using GIVEN-WHEN-THEN and SCENARIO documentation an additional procedure documentation is really not necessary.
I will discuss this...currently I'm thinking about something similar to the `exportScope` config to control the dignostics output.

Regarding `OnAfterGetRecord` and other `trigger` procedures you're absolutly right! This should not happen. In current version 0.4.1 `trigger` procedures are not included in the diagnostics and do not complain about missing documentations
![image](https://user-images.githubusercontent.com/39621236/88152472-5a96f700-cc04-11ea-9c79-7ae1f7ddeb89.png)

Could you pls check which version do you've installed? Previous version 0.4.0 is checking `trigger` procedures, but 0.4.1 does not.

**Comment by StefanMaron** [comment]
Version is already 4.1 so trigger are fine ;)

**Comment by sirhc101** [comment]
We decided to add an additional configuration setting to control which kind of procedures will be checked.

**Comment by sirhc101** [comment]
Hello @StefanMaron,

we've added the following implementation and will ship this with the upcoming release 0.4.2.

In `settings.json` you can add the new configuration element `bdev-al-xml-doc.procedureTypes`. It supports the following selection types:

- Global Procedures
- Local Procedures
- Internal Procedures
- Event Publisher
- Event Subscriber
- Trigger Procedures
- Test Procedures

The configuration is similar to what you may know from the CodeAnalyzer in AL language. So it's just a list of types you want to process with the extension. 
![image](https://user-images.githubusercontent.com/39621236/88389602-1435c980-cdb7-11ea-8a43-1e5dd0d5f08e.png)

From that point every feature of our extension will only take place for the configured procedure types.

We hope this fits you need.
