### ISSUE TITLE
Only one Index.md for whole Project

### ISSUE THREAD

**Issue by MacWin77** [365businessdev/vscode-alxmldocumentation#49]
Hello :-) 
Is there a possibility to just create one Index.md for the whole project? 
Current Version looks like this 
/doc
/doc/Object1Dir/index.md 
 - Contains md files for function summarys
/doc/Object2Dir/index.md
 - Contains md files for function summarys
/doc/Object3Dir/index.md
 - Contains md files for function summarys
I want to create a folder structure like this

/doc
/doc/Object1Dir/
 - Contains md files for function summarys
/doc/Object2Dir/
 - Contains md files for function summarys
/doc/Object3Dir/
 - Contains md files for function summarys
/doc/index.md (Navigation to every function summary md file

**Example** 
![image](https://user-images.githubusercontent.com/72028220/108869124-2c90ef80-75f7-11eb-98f5-4cb51ed54718.png)

**Comment by spookymattress** [comment]
I vote for this enhancement as well!! 😜

**Comment by sirhc101** [comment]
We're currently working on the newest version, including the completely re-designed documentation markdown export. We added this enhancement to our backlog and will allow configuration to select creating one index file per project, per file or both.

Stay tuned, we plan to release the new version in next 2 weeks.

**Comment by sirhc101** [comment]
Hello @spookymattress & @MacWin77,

We've now our first beta version up and running and started some discussion in the team regarding the structure of the documentation (md) files generated. Current state is following:

- Each AL Object result in **one** markdown file, named like the AL file. This file includes the object description and each procedure, including params, obsolete reason, etc.<br>
![image](https://user-images.githubusercontent.com/39621236/112890221-e5ef5300-90d6-11eb-8975-a1f3ddf84010.png)
<br><br>Looks like this:
![image](https://user-images.githubusercontent.com/39621236/112889674-3dd98a00-90d6-11eb-8be7-43fffd33e74d.png)
- Additionally per project one `index.md` file is created, including the app details from app.json (version, description, publisher, dependencies) and a grouped list of all objects. If an object description is present this will directly be printed below the object name. The object is linked to the specific AL Object markdown file.<br><br>Currently looks like this:
![image](https://user-images.githubusercontent.com/39621236/112890059-b2142d80-90d6-11eb-8949-c86de9edca64.png)

Now while we discussed this in the team the original idea of creating one file per project, per object and per procedure came back. Because you guys asked for it ... what do you think? 
File per project (index), object (index) and procedure
vs.
File per project (index) and object including all procedures

Thank you very much.

**Comment by spookymattress** [comment]
In daily use and for small-medium size projects I think I would go for File per project (index) and object including all procedures

But in large projects it could be nice to do:
File per project (index), object (index) and procedure

Could it be a config option you could set yourself?

**Comment by sirhc101** [comment]
@spookymattress Thank you. Yes, this are the same arguments which come into my mind. In large projects with APIs and stuff it's much more transparent. I will introduce a specific configuration for this.

**Comment by spookymattress** [comment]
Cool, any idea when the new release will be available?

**Comment by sirhc101** [comment]
We're planning to release version 1.1.0 on April 16th.

From our backlog we have all but two work items finished and completely tested, so I think we're in plan.
