### ISSUE TITLE
Feature Request: Support VS Code workspaces

### ISSUE THREAD

**Issue by RafaelKoch** [365businessdev/vscode-alxmldocumentation#73]
Today the extension does not support workspaces, so i.e. when generating documentation all docs get placed in the first app folder and not all al files get processed. The workaround is to open every app as separate folder. It would be very convenient if workspaces would be supported.

**Comment by ChristianBraeunlich** [comment]
This got fixed in https://github.com/365businessdev/vscode-alxmldocumentation/issues/62 and released in v1.1.4. I just tested it with the latest v1.1.6 release and everything still works.

Add `"al-xml-doc.DocumentationExportPath": "${workspaceFolder}/docs"` to the settings section of your .code-workspace file.
